inc:
  # Blog Information
  title:        "Amplified Blog"
  subtitle:     "Some noises about our loved amplified"
  cover_image:  amplified-index.jpg
  logo:         logo.png

  # Company information
  company:      Amplified
  url:          http://amplifiedapp.com/
  facebook:     amplifiedapp
  twitter:      amplifiedapp
  gplus:        ''
  about_link:   http://amplifiedapp.com/about/

  # Product Information
  product_link: http://amplifiedapp.com/
  tagline:      "Your band rehearsals. Enhanced."

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://amplifiedapp.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['vendor']
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
